name: Download JSON
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download and compare files
        run: python scripts/download_json.py
      - name: Commit new versions of files
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: "Downloaded new versions of JSON documents"
          default_author: github_actions
