# This is a basic workflow that is manually triggered

name: Load spreadsheet data

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      sheetUrl:
        description: 'Google Spreadsheet to be parsed'
        required: true

jobs:
  # This workflow contains a single job called "greet"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Log id
      run: echo "Loading ${{ github.event.inputs.sheetUrl }}"
    - name: Bring in repo
      uses: actions/checkout@v2
      with:
        ref: 'GS-update'
    - name: install Python dependencies
      run: |
        python -m pip install -U pip
        pip install -r scripts/gs_requirements.txt
    - name: generate ttl files
      run: |
        echo 'generating ttl...'
          url="${{ github.event.inputs.sheetUrl }}"
          outd="specification-elements/defs/gsheet-import"
          python scripts/fetch_gs_data.py -u $url -o $outd
          ls -ltr specification-elements/defs/gsheet-import
    - name: commit normalised input from spreadsheet
      uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        add: .
        message: "Generated definitions from spreadsheet"
        default_author: github_actions
