# This is a basic workflow that is manually triggered

name: Load spreadsheet data

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      sheetUrl:
        description: 'Google Spreadsheet to be parsed'
        required: true

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Loading ${{ github.event.inputs.sheetUrl }}"
